services:
install:

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.39.0/selenium-java-2.39.0.jar"
  - "java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
  - composer install
  - php -S localhost:8000 -t ./ &
language: php
php:
  - 5.4
  - 5.5
  - 5.6
script:
  - ./vendor/bin/phpunit