services:

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
  - "java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
  - composer install
  - php -S localhost:8000 -t home/travis/build/ThiagoToledoPHP/Copacabana/ &
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
script:
  - ./vendor/bin/phpunit